add missing import
still dying on the following error now (manual Singularity exec testing
of ParameterRuns.jl)

```
  Activating project at `/code`
ERROR: LoadError: MethodError: Cannot `convert` an object of type StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64} to an object of type Float64
Closest candidates are:
  convert(::Type{T}, ::Base.TwicePrecision) where T<:Number at /opt/julia-1.7.3/share/julia/base/twiceprecision.jl:262
  convert(::Type{T}, ::AbstractChar) where T<:Number at /opt/julia-1.7.3/share/julia/base/char.jl:185
  convert(::Type{T}, ::CartesianIndex{1}) where T<:Number at /opt/julia-1.7.3/share/julia/base/multidimensional.jl:136
  ...
Stacktrace:
  [1] (::Base.var"#898#900")(x::Task)
    @ Base ./asyncmap.jl:177
  [2] foreach(f::Base.var"#898#900", itr::Vector{Any})
    @ Base ./abstractarray.jl:2712
  [3] maptwice(wrapped_f::Function, chnl::Channel{Any}, worker_tasks::Vector{Any}, c::Vector{Dict{Symbol, Any}})
    @ Base ./asyncmap.jl:177
  [4] wrap_n_exec_twice
    @ ./asyncmap.jl:153 [inlined]
  [5] #async_usemap#883
    @ ./asyncmap.jl:103 [inlined]
  [6] #asyncmap#882
    @ ./asyncmap.jl:81 [inlined]
  [7] pmap(f::Function, p::WorkerPool, c::Vector{Dict{Symbol, Any}}; distributed::Bool, batch_size::Int64, on_error::Nothing, retry_delays::Vector{Any}, retry_check::Nothing)
    @ Distributed /opt/julia-1.7.3/share/julia/stdlib/v1.7/Distributed/src/pmap.jl:126
  [8] pmap(f::Function, p::WorkerPool, c::Vector{Dict{Symbol, Any}})
    @ Distributed /opt/julia-1.7.3/share/julia/stdlib/v1.7/Distributed/src/pmap.jl:101
  [9] pmap(f::Function, c::Vector{Dict{Symbol, Any}}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Distributed /opt/julia-1.7.3/share/julia/stdlib/v1.7/Distributed/src/pmap.jl:156
 [10] pmap(f::Function, c::Vector{Dict{Symbol, Any}})
    @ Distributed /opt/julia-1.7.3/share/julia/stdlib/v1.7/Distributed/src/pmap.jl:156
 [11] parameters_experiment(conds::Dict{Symbol, Any})
    @ SpatialRust /code/src/Runners.jl:17
 [12] top-level scope
    @ /code/scripts/ParameterRuns.jl:41
```