add initial Dockerfile
should replace with opensciencegrid/osvgo-julia image eventually

image currently does not build due to julia compilation errors,
appears to be due to WebIO, e.g., executing

`% docker build -t comses/spatialrustmodel .` eventually leads to

```

┌ Warning: Could not use exact versions of packages in manifest, re-resolving
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:
1488                                                                                                           ERROR: LoadError: Error building `WebIO`:                                                                      [ Info: Downloading WebIO core bundle from unpkg...
ERROR: LoadError: HTTP/2 404 while requesting https://pkg.julialang.org/binary/WebIO.jl/v0.8.90/webio.bundle.js
Stacktrace:
  [1] #3
    @ /opt/julia-1.7.3/share/julia/stdlib/v1.7/Downloads/src/Downloads.jl:243 [inlined]
  [2] open(f::Downloads.var"#3#4"{Nothing, Vector{Pair{String, String}}, Float64, Pkg.PlatformEngines.var"#16#1
8", Bool, Nothing, Nothing, String}, args::String; kwargs::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(
:write,), Tuple{Bool}}})
    @ Base ./io.jl:330
  [3] arg_write(f::Function, arg::String)
    @ ArgTools /opt/julia-1.7.3/share/julia/stdlib/v1.7/ArgTools/src/ArgTools.jl:86
  [4] #download#2                                                                                                  @ /opt/julia-1.7.3/share/julia/stdlib/v1.7/Downloads/src/Downloads.jl:230 [inlined]
  [5] download(url::String, dest::String; verbose::Bool, headers::Vector{Pair{String, String}}, auth_header::No
thing, io::IOContext{IOStream})
    @ Pkg.PlatformEngines /opt/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/PlatformEngines.jl:282
  [6] download(url::String, dest::String)
```